repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "2c9f875913ee60ca25ce70243dc24d5b6415598c" # v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
  - repo: https://github.com/rhysd/actionlint
    rev: "c6bd06256dd700a45e483869bcdcf304239393a6" # v1.6.27
    hooks:
      - id: actionlint-docker
        args: [-pyflakes=]
