site_name: mkdocs-sandbox
site_description: Sandbox project for mkdocs
site_author: mkdocs-sandbox
repo_url: https://github.com/iacabezasbaculima/mkdocs-sandbox
edit_uri: edit/main/docs

nav:
  - Homepage:
      - index.md
      - SectionA:
        - page1.md
      - SectionB:
        - page2.md
        - page3.md
      - SectionC:
        - page4.md
        - page5.md
        - page6.md
      - SectionD:
        - page7.md
        - page8.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides

markdown_extensions:
  - abbr
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - git-revision-date
  - search
  - mike:
      alias_type: copy

extra:
  version:
    provider: mike
    default: latest
