name: Release Docs

on:
  push:
    tags:
      - v*.*.*

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: release-docs
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      # https://github.com/orgs/community/discussions/26560
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build docs website and API reference
        run: |
          VERSION="$(echo ${{ github.ref_name }} | tr -d v)"
          make release-docs VERSION="$VERSION" ALIAS="latest"
          poetry run mike set-default --push latest

  dpeloy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
