name: Publish Docs

on:
  workflow_call:
    inputs:
      version:
        description: "Version to build and publish docs"
        required: true
        type: string
      git_ref:
        description: "Branch or commit ID to checkout from"
        required: false
        type: string
        default: main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: release-docs
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ inputs.git_ref }}
          fetch-depth: 0

      # https://github.com/orgs/community/discussions/26560
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version-file: '.python-version'
          cache: "poetry"

      - name: Install dependencies
        shell: bash
        run: poetry install --no-root

      - name: Build docs
        shell: bash
        env:
          VERSION: ${{ inputs.version }}
        run: |
          make release-docs VERSION="$VERSION" ALIAS="latest"
          poetry run mike set-default --push latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: gh-pages

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: .

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e	# v4.0.5
